language: c
compiler:
  - clang
  - gcc

install:
  - ./travis.sh getplugins || true
  
before_script:
  - uname -a

script:
  - ./travis.sh build $CONFIGURE_FLAGS

env:
  - CONFIGURE_FLAGS="--enable-debug"
  
notifications:
  email: false
  
branches:
  except:
    - rathena
